version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 654654318481.dkr.ecr.eu-west-2.amazonaws.com
  build:
    commands:
      - docker build -t reservations -f ./apps/reservations/Dockerfile .
      - docker tag revervations:latest 654654318481.dkr.ecr.eu-west-2.amazonaws.com/revervations:latest
      -
      - docker build -t auth -f ./apps/auth/Dockerfile .
      - docker tag auth:latest 654654318481.dkr.ecr.eu-west-2.amazonaws.com/auth:latest
      -
      - docker build -t payments -f ./apps/payments/Dockerfile .
      - docker tag payments:latest 654654318481.dkr.ecr.eu-west-2.amazonaws.com/payments:latest
      -
      - docker build -t notifications -f ./apps/notifications/Dockerfile .
      - docker tag notifications:latest 654654318481.dkr.ecr.eu-west-2.amazonaws.com/notifications:latest
  post_build:
    commands:
      - docker push 654654318481.dkr.ecr.eu-west-2.amazonaws.com/revervations:latest
      - docker push 654654318481.dkr.ecr.eu-west-2.amazonaws.com/auth:latest
      - docker push 654654318481.dkr.ecr.eu-west-2.amazonaws.com/payments:latest
      - docker push 654654318481.dkr.ecr.eu-west-2.amazonaws.com/notifications:latest
